lint:
  parameters:
    concurrency:
      type: integer
      default: 2
  executor: node
  steps:
    - checkout
    # installation of dependencies takes a while because of the 100 packages we have inside the monorepo
    # Linting only needs the root packages, we remove the workspace and only install root packages
    - run:
        name: "remove workspaces from package.json"
        command: |
          sed -i ':a;N;$!ba;s/,\n\s*"workspaces":\s\[[^]]*]//g' package.json
    - node/install-packages:
        pkg-manager: yarn
        cache-name: no-workspace
        cache-path: ~/.cache
    - run: yarn npm-run-all -p lint:code lint:docs lint:other --aggregate-output --max-parallel=<< parameters.concurrency >>
    - run: yarn lint:docs
    - run: yarn lint:other

typecheck:
  executor: node
  steps:
    - checkout
    - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
    - attach_workspace:
        at: ./
    - run: yarn typecheck
    - run: yarn check-repo-fields
