unit_tests_node:
  executor: node
  steps: &test_template
    - checkout
    - run: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
    - attach_workspace:
        at: ./
    - run:
        matrix:
          parameters:
            version:
              - 10.13.0
              - 12
        name: Run tests
        command: yarn jest --ci -runInBand
        environment:
          NODE_OPTIONS: --max-old-space-size=2048
          GENERATE_JEST_REPORT: true
          JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
          JEST_JUNIT_OUTPUT_NAME: results.xml
    - store_test_results:
        path: ./test-results/jest-node/
