aliases:
  node-linux-executor: &node-linux-executor
    parameters:
      concurrency:
        type: integer
        default: 2
    executor: node

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: ./
